name: Create Release

on:
  push:
    tags:

jobs:
  create_release:
    name: Create Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v2

      - name: Release
        run: |
          tag = $(echo "${{ vars.GITHUB_REF }}" | sed 's|refs/tags/||')
          git clone https://github.com/grpc/grpc-swift/tree/$tag && cd grpc-swift && swift create-xcframework
